# -*- coding: utf-8 -*-
"""szkolenie_1dzien.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roPFZdwefa_PnYtGaW3LxMDM7sgm8IHm
"""

2+6



print("hello world")

"""# napis

### Napis

**Tekst123**

1.   List item
2.   List item
"""

